# Generated by Django 3.1.7 on 2021-03-10 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invite.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_activated', models.BooleanField(default=False, verbose_name='Профиль активирован')),
                ('expire_at', models.DateTimeField(default=invite.models.invite_default_expire_at)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('password_changed', models.BooleanField(default=False, verbose_name='Пароль изменён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инвайт',
                'verbose_name_plural': 'Инвайты',
            },
        ),
    ]
