# Generated by Django 3.1.7 on 2021-03-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'Приглашение', 'verbose_name_plural': 'Прилглашения'},
        ),
    ]
