# Generated by Django 3.1.7 on 2021-03-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_auto_20210320_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'Приглашение', 'verbose_name_plural': 'Приглашения'},
        ),
    ]
