# Generated by Django 3.1.7 on 2021-03-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0004_auto_20210320_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geo',
            options={'verbose_name': 'Гео', 'verbose_name_plural': 'Гео'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Персональные данные', 'verbose_name_plural': 'Персональные данные'},
        ),
    ]
