# Generated by Django 3.1.7 on 2021-03-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0005_auto_20210320_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RenameField(
            model_name='geo',
            old_name='lon',
            new_name='geo_lat',
        ),
        migrations.RenameField(
            model_name='geo',
            old_name='lat',
            new_name='geo_lon',
        ),
        migrations.RemoveField(
            model_name='geo',
            name='label',
        ),
        migrations.RemoveField(
            model_name='geo',
            name='parent',
        ),
        migrations.AddField(
            model_name='geo',
            name='area',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название района'),
        ),
        migrations.AddField(
            model_name='geo',
            name='area_fias_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИАС ID района'),
        ),
        migrations.AddField(
            model_name='geo',
            name='area_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип района'),
        ),
        migrations.AddField(
            model_name='geo',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер строения'),
        ),
        migrations.AddField(
            model_name='geo',
            name='block_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип строения'),
        ),
        migrations.AddField(
            model_name='geo',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название города'),
        ),
        migrations.AddField(
            model_name='geo',
            name='city_district',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название района города'),
        ),
        migrations.AddField(
            model_name='geo',
            name='city_district_fias_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИАС ID района города'),
        ),
        migrations.AddField(
            model_name='geo',
            name='city_district_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип района города'),
        ),
        migrations.AddField(
            model_name='geo',
            name='city_fias_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИАС ID города'),
        ),
        migrations.AddField(
            model_name='geo',
            name='city_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип города'),
        ),
        migrations.AddField(
            model_name='geo',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='geo',
            name='country_iso_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ISO код страны'),
        ),
        migrations.AddField(
            model_name='geo',
            name='federal_district',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Федеральный округ'),
        ),
        migrations.AddField(
            model_name='geo',
            name='fias_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИАС код адреса'),
        ),
        migrations.AddField(
            model_name='geo',
            name='fias_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИАС ID адреса'),
        ),
        migrations.AddField(
            model_name='geo',
            name='fias_level',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Уровень ФИАС кода'),
        ),
        migrations.AddField(
            model_name='geo',
            name='house',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='geo',
            name='house_fias_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИАС ID дома'),
        ),
        migrations.AddField(
            model_name='geo',
            name='house_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип дома'),
        ),
        migrations.AddField(
            model_name='geo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='geo',
            name='region',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название области'),
        ),
        migrations.AddField(
            model_name='geo',
            name='region_fias_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИАС ID области'),
        ),
        migrations.AddField(
            model_name='geo',
            name='region_iso_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO код области'),
        ),
        migrations.AddField(
            model_name='geo',
            name='region_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип области'),
        ),
        migrations.AddField(
            model_name='geo',
            name='settlement',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название населённого пункта'),
        ),
        migrations.AddField(
            model_name='geo',
            name='settlement_fias_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИАС ID населённого пункта'),
        ),
        migrations.AddField(
            model_name='geo',
            name='settlement_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип населённого пункта'),
        ),
        migrations.AddField(
            model_name='geo',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название улицы'),
        ),
        migrations.AddField(
            model_name='geo',
            name='street_fias_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИАС ID улицы'),
        ),
        migrations.AddField(
            model_name='geo',
            name='street_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип улицы'),
        ),
    ]
