# Generated by Django 3.1.7 on 2021-03-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veche', '0001_initial'),
        ('personal_cabinet', '0008_profile_geo_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='geo_community',
        ),
        migrations.AddField(
            model_name='profile',
            name='geo_community',
            field=models.ManyToManyField(blank=True, null=True, related_name='geo_community', to='veche.Community'),
        ),
    ]
