# Generated by Django 3.1.7 on 2021-03-31 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0010_auto_20210331_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='geo',
        ),
        migrations.AddField(
            model_name='geo',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='personal_cabinet.profile'),
        ),
    ]
