# Generated by Django 3.1.7 on 2021-04-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0013_auto_20210331_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='personal_cabinet.profile'),
        ),
    ]
