# Generated by Django 3.1.7 on 2021-04-14 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('open', 'открыта'), ('agreed', 'принята'), ('rejected', 'отклонена')], default='open', max_length=20, verbose_name='Статус заявки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veche.community')),
            ],
            options={
                'verbose_name': 'Заявка на вступление в сообщество',
                'verbose_name_plural': 'Заявки на вступление в сообщество',
            },
        ),
        migrations.CreateModel(
            name='RequestResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания')),
                ('resolution', models.CharField(choices=[('agreed', 'принята'), ('rejected', 'отклонена')], max_length=20, verbose_name='Решение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veche.communityrequest')),
            ],
            options={
                'verbose_name': 'Решение по заявке на вступление в сообщество',
                'verbose_name_plural': 'Решения по заявке на вступление в сообщество',
            },
        ),
    ]
