# Generated by Django 3.1.7 on 2021-04-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veche', '0003_auto_20210416_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityrequest',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_requests', to='veche.community'),
        ),
    ]
