# Generated by Django 3.1.7 on 2021-05-21 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import veche.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veche', '0005_auto_20210422_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата правки')),
                ('initiative_label', models.CharField(max_length=100, verbose_name='Заголовок инициативы')),
                ('initiative_text', models.TextField(verbose_name='Текст инициативы')),
                ('expire_at', models.DateTimeField(default=veche.models.initiative_default_expire_at)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_initiatives', to='veche.community')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
