# Generated by Django 3.1.7 on 2021-05-21 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veche', '0006_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='min_agree_percent',
            field=models.PositiveIntegerField(default=0.75, verbose_name='Минимальный процент одобрений'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('open', 'открыта'), ('agreed', 'принята'), ('rejected', 'отклонена')], default='open', max_length=20, verbose_name='Статус инициативы'),
        ),
        migrations.CreateModel(
            name='MessageInitiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата правки')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Initiative_messages', to='veche.initiative')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
