# Generated by Django 3.1.7 on 2021-05-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veche', '0007_auto_20210521_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageinitiative',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_messages', to='veche.initiative'),
        ),
    ]
