# Generated by Django 3.1.7 on 2021-05-25 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veche', '0008_auto_20210525_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionInitiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('resolution', models.CharField(choices=[('agreed', 'принята'), ('rejected', 'отклонена')], max_length=20, verbose_name='Решение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_resolutions', to='veche.initiative')),
            ],
            options={
                'verbose_name': 'Решение по заявке на вступление в сообщество',
                'verbose_name_plural': 'Решения по заявке на вступление в сообщество',
            },
        ),
    ]
