# Generated by Django 3.1.7 on 2021-05-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veche', '0009_resolutioninitiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='involved_communities',
            field=models.ManyToManyField(blank=True, null=True, related_name='involved_communities', to='veche.Community'),
        ),
    ]
