# Generated by Django 3.1.7 on 2021-06-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veche', '0011_auto_20210531_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolutioninitiative',
            options={'verbose_name': 'Решение по инициативе', 'verbose_name_plural': 'Решения по инициативе'},
        ),
    ]
