# Generated by Django 3.1.7 on 2021-06-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veche', '0012_auto_20210602_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolutioninitiative',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст решения'),
        ),
    ]
